### ISSUE TITLE
invalid field name

### ISSUE THREAD

**Issue by mitchjacksontech** [strategicdata/log-gelf-util#8]
Recent updates added fatal checks for validation of field names. This update breaks all my apps using Log::Gelf::Util, because I often dump a ton of indiscriminate debugging data to GELF during troubleshooting or error reporting that may not pass these checks. For example:

> Caught exception in engine "invalid field name '_charset=utf-8' at /Users/xyz/perl5/perlbrew/perls/perl-5.28.1/lib/site_perl/5.28.1/Log/GELF/Util.pm line 168."

Changelog makes no mention of breaking changes, and does not mention this new fatal validation check.

Could these checks throw a warning, or have a config setting allowing them to be non fatal?

**Comment by adamc00** [comment]
The change in behaviour you are seeing is due to a recent bugfix. The library was always supposed to be validating the fields.

I suspect there's a recommended way to handle your use case. I will take a look and update the issue once I've had a chance.

**Comment by adamc00** [comment]
My suggestion is that you preprocess your debug data to prepend the supported underscore prefix to your fields or encode them as a json string and append them to a single additional field. See "_[additional field]" in https://go2docs.graylog.org/current/getting_in_log_data/gelf.html.

**Comment by mitchjacksontech** [comment]
Hi, thanks for the suggestion. Will pin old version of the library until I can update all our logging tools to mitigate the new intentional crashing behavior caused by the validation bugfix 👍

**Comment by adamc00** [comment]
Let me know if you have any problems with that approach. I'm going to make sure the json approach is tested and works. Will fix if not.
